name: Test and Run ML Model

on: pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"
      - name: Install dependencies
        run: poetry install
      - name: Lint code
        id: lint
        run: ./lint.sh
      - name: Run tests
        if: steps.lint.outcome == 'success'
        run: ./test.sh
